{
  imports = [
    ./treesitter.nix
    ./blink-cmp.nix
    ./fzf-lua.nix
    ./gitsigns.nix
    ./lualine.nix
    ./bufferline.nix
    ./which-key.nix
    ./conform.nix
    ./autopairs.nix
    ./surround.nix
    ./toggleterm.nix
    ./undo-tree.nix
    ./snacks.nix
    ./comment.nix
    ./yazi.nix
    ./lazygit.nix
    ./code-runner.nix
  ];
}
